FROM python:3.12-slim-bookworm

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        wait-for-it \
        wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN python -m venv venv

COPY ./web/requirements.txt web-requirements.txt
COPY ./web/isithot/requirements.txt isithot-requirements.txt

ENV \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

RUN venv/bin/pip install wheel
RUN venv/bin/pip install -r isithot-requirements.txt -r web-requirements.txt

COPY web web
COPY database database

RUN venv/bin/pybabel compile -d web/isithot/translations
