CREATE TABLE IF NOT EXISTS lmss_daily(
    date TIMESTAMP PRIMARY KEY,
    temp_mean_mannheim NUMERIC
);

CREATE TABLE IF NOT EXISTS lmss_garden_raw (
    date TIMESTAMP PRIMARY KEY,
    battery_voltage_mean NUMERIC,
    battery_voltage_min NUMERIC,
    battery_voltage_max NUMERIC,
    ac_voltage_mean NUMERIC,
    ac_voltage_min NUMERIC,
    ac_voltage_max NUMERIC,
    relhum_mean NUMERIC,
    relhum_min NUMERIC,
    relhum_max NUMERIC,
    temp_mean NUMERIC,
    temp_min NUMERIC,
    temp_max NUMERIC,
    relhum_mean_2 NUMERIC,
    relhum_min_2 NUMERIC,
    relhum_max_2 NUMERIC,
    temp_mean_2 NUMERIC,
    temp_min_2 NUMERIC,
    temp_max_2 NUMERIC,
    surface_temp_mean NUMERIC,
    surface_temp_min NUMERIC,
    surface_temp_max NUMERIC,
    soil_temp_10_mean NUMERIC,
    soil_temp_10_min NUMERIC,
    soil_temp_10_max NUMERIC,
    soil_temp_20_mean NUMERIC,
    soil_temp_20_min NUMERIC,
    soil_temp_20_max NUMERIC,
    soil_temp_50_mean NUMERIC,
    soil_temp_50_min NUMERIC,
    soil_temp_50_max NUMERIC,
    soil_temp_100_mean NUMERIC,
    soil_temp_100_min NUMERIC,
    soil_temp_100_max NUMERIC,
    precipitation_sum NUMERIC,
    dew_point_temp_mean NUMERIC,
    dew_point_temp_min NUMERIC,
    dew_point_temp_max NUMERIC,
    dew_point_temp_mean_2 NUMERIC,
    dew_point_temp_min_2 NUMERIC,
    dew_point_temp_max_2 NUMERIC,
    abshum_mean NUMERIC,
    abshum_min NUMERIC,
    abshum_max NUMERIC
);
